---
- hosts: all
#  remote_user: ubuntu
  become: yes
#  gather_facts: false
  tasks:
    - name: check host name
      shell: hostname
      register: hostname_server
    - name: show OS version
      shell: cat /etc/issue
      register: os_version
    - name: check Openssl version for Debian
      shell: dpkg -l | grep openssl
      register: openssl_versiondeb
      when: ansible_os_family == "Debian"
    - name: check Openssl version for "Linux"
      shell: rpm -qa | grep openssl
      register: openssl_versionyum
      when: ansible_os_family == "Redhat"
    - name: create a local output file
      local_action: shell echo 'Servername;OS-Version;Openssl-Version' | tee myfile.csv
    - name: update details to the file deb
      local_action: shell echo '{{ hostname_server.stdout }};{{ os_version.stdout }};{{ openssl_versiondeb.stdout }}' | tee -a myfile.csv
      when: ansible_os_family == "Debian"
    - name: update details to when yum
      local_action: shell echo '{{ hostname_server.stdout }};{{ os_version.stdout }};{{ openssl_versionyum.stdout}}' | tee -a myfile.csv
      when: ansible_os_family == "Redhat"

#    - local_action: shell echo {{ out.stdout }} >> file
#      sudo: no
      
#debug: var=out.stdout_lines
#    - name: show openssl version
#      shell: dpkg -l | grep openssl
#      register: out
#    - debug: var=out.stdout_lines
